export const SEARCH_DEFAULTS = {
  RADIUS_METERS: 15000,
  MAX_RADIUS_METERS: 50000,
  MIN_RADIUS_METERS: 500,
  PAGE_LIMIT: 20,
  MAX_PAGE_LIMIT: 50,
} as const

export const REVIEW_DEFAULTS = {
  PAGE_LIMIT: 10,
  MAX_PAGE_LIMIT: 50,
  MAX_COMMENT_LENGTH: 2000,
  MIN_RATING: 1,
  MAX_RATING: 5,
} as const
